import type { ImportedGPSSession } from './dataLoggerImport'

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  setTimeout(() => URL.revokeObjectURL(url), 5000)
}

// Convert #RRGGBB → KML AABBGGRR (alpha=ff)
function hexToKml(hex: string): string {
  const h = hex.replace('#', '')
  const r = h.slice(0, 2), g = h.slice(2, 4), b = h.slice(4, 6)
  return `ff${b}${g}${r}`
}

export function exportGPX(session: ImportedGPSSession): void {
  const trkpts = session.points.map(p => {
    const iso = new Date(p.timeS * 1000).toISOString()
    const extLines = [
      p.speedKmh   != null ? `<speed>${(p.speedKmh / 3.6).toFixed(2)}</speed>` : '',
      p.rpm        != null ? `<rpm>${p.rpm.toFixed(0)}</rpm>` : '',
      p.throttlePct != null ? `<throttle>${p.throttlePct.toFixed(1)}</throttle>` : '',
    ].filter(Boolean)
    return [
      `    <trkpt lat="${p.lat.toFixed(7)}" lon="${p.lon.toFixed(7)}">`,
      `      <time>${iso}</time>`,
      extLines.length ? `      <extensions>${extLines.join('')}</extensions>` : '',
      `    </trkpt>`,
    ].filter(Boolean).join('\n')
  }).join('\n')

  const gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Kart Connect"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <trk>
    <name>${session.driverLabel}</name>
    <src>${session.brand} via Kart Connect</src>
    <trkseg>
${trkpts}
    </trkseg>
  </trk>
</gpx>`

  download(new Blob([gpx], { type: 'application/gpx+xml' }), `${session.driverLabel}.gpx`)
}

export function exportKML(sessions: ImportedGPSSession[], colors: string[]): void {
  const placemarks = sessions.map((s, i) => {
    const coords = s.points.map(p => `${p.lon.toFixed(7)},${p.lat.toFixed(7)},0`).join(' ')
    const kmlColor = hexToKml(colors[i % colors.length])
    return `  <Placemark>
    <name>${s.driverLabel} (${s.brand})</name>
    <Style>
      <LineStyle><color>${kmlColor}</color><width>3</width></LineStyle>
    </Style>
    <LineString>
      <tessellate>1</tessellate>
      <coordinates>${coords}</coordinates>
    </LineString>
  </Placemark>`
  }).join('\n')

  const kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
  <name>Kart Connect — GPS Comparison</name>
  <description>Generated by Kart Connect. Open in Google Earth to overlay all drivers.</description>
${placemarks}
</Document>
</kml>`

  download(new Blob([kml], { type: 'application/vnd.google-earth.kml+xml' }), 'kart-connect-gps-comparison.kml')
}

export function exportNormalizedCSV(sessions: ImportedGPSSession[]): void {
  const header = 'driver,brand,time_s,lat,lon,speed_kmh,rpm,throttle_pct,lap,distance_m'
  const rows = sessions.flatMap(s =>
    s.points.map(p =>
      [
        `"${s.driverLabel}"`,
        s.brand,
        p.timeS.toFixed(3),
        p.lat.toFixed(7),
        p.lon.toFixed(7),
        p.speedKmh?.toFixed(1) ?? '',
        p.rpm?.toFixed(0) ?? '',
        p.throttlePct?.toFixed(1) ?? '',
        p.lapNumber ?? '',
        p.distanceM.toFixed(1),
      ].join(',')
    )
  )

  download(
    new Blob([[header, ...rows].join('\n')], { type: 'text/csv' }),
    'kart-connect-gps-normalized.csv',
  )
}
