import type { SetupFormData } from '@/types'

export const setupDefaults: Partial<SetupFormData> = {
  chassis_type:          '',
  engine_type:           '',
  rear_bumper:           null,
  rear_width_mm:         1000,
  rear_hub_length_mm:    85,
  third_bearing:         false,
  axle_height:           'Med',
  brake_pads:            'Med',
  rear_sprocket_teeth:   82,
  engine_sprocket_teeth: 11,
  sprocket_carrier_type: 'Fixed',
  chain_measurement:     '219',
  spark_plug:            'NGK BR10EG',
  main_jet:              '108',
  air_screw:             '1.5 turns out',
  needle_position:       'Clip 3 from top',
  front_width_mm:        730,
  front_hub_length_mm:   30,
  right_height:          'Med',
  camber:                '0.0',
  caster:                '15',
  toe:                   '0',
  stub_axle:             'Hard',
  wheel_type:            'Summer',
  tyre_make:             '',
  tyre_model:            '',
  tyre_pressure_fl:      0.80,
  tyre_pressure_fr:      0.80,
  tyre_pressure_rl:      0.80,
  tyre_pressure_rr:      0.80,
  tape_over_rad:         null,
  max_rpm:               null,
  low_rpm:               null,
  max_engine_temp_c:     null,
  low_engine_temp_c:     null,
  max_exhaust_temp_c:    null,
  low_exhaust_temp_c:    null,
  float_height:          null,
  carb_year:             null,
  brake_bias_pct:        null,
  chassis_make:          null,
  engine_number:         null,
  engine_rank:           null,
  kart_driver_weight_kg: null,
  seat_hardness:         null,
  seat_bolts_front:      null,
  seat_bolts_back:       null,
}
