[functions.guest-session-read]
verify_jwt = false

[functions.guest-session-save]
verify_jwt = false

[functions.cron-expire-weekends]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
